-->Thanks to http://www.glassgiant.com/ for the providing of the ascii codes
--->feel free to modifie, just remember to leve these three lines here^^

print("\27[1;32m                        DDD             ")
print("        DDD            D??7D  D         ")
print("     DD7???7DD        DI????DD77D       ")
print("     D???????7D       DIIIII7III7D      ")
print("     DD77777777D      D$$$$$$$$$$D      ")
print("    D7ZZZZZZZZZ8      DOOOOOOOOO7D      ")
print("\27[0;32m   D888888888888D     DDDDDDDDD7D       ")
print("   D7DDDDDDDDDDDD     D7DDDDD8DD        ")
print("    DDD77777DDDD       DDD7DD8          ")
print("                       OD               ")
print("                                        ")
print("                                        ")
print("                                        ")
print("\27[1;32m           DD77D      DDDDD$$DDDD       ")
print("        8D7????7D    D???????????7D     ")
print("       D7I??????D    D7IIIIIIIIIIIDD    ")
print("      D7777777777D    D$$$$$$$$$$DD     ")
print("\27[0;32m     DDZZZZZZZZZZD    D7OOOOO7DDD       ")
print("     8D8888888888D     D7DDDDDD$D       ")
print("      D7DD7DDDDDDD      DD$DDDDZD       ")
print("       DDDDDDDDD87        DDDDD         ")
print("             DDDD                       ")
print("\27[0;0m")
